name: Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ] # Triggers whenever push to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build all JARs first
      - name: Build JAR files
        run: mvn clean package -DskipTests

      # Build and Push Config Server
      - name: Build and Push Config Server
        uses: docker/build-push-action@v5
        with:
          context: ./Backend/ConfigServer
          push: true
          tags: hemantbarole/micro-config-server:latest

      # Build and Push Discovery Service
      - name: Build and Push Discovery
        uses: docker/build-push-action@v5
        with:
          context: ./Backend/ServiceRegistry
          push: true
          tags: hemantbarole/micro-service-registry:latest

      # Build and Push auth Service
      - name: Build and Push Discovery
        uses: docker/build-push-action@v5
        with:
          context: ./Backend/AuthServer
          push: true
          tags: hemantbarole/micro-auth-server:latest
      
      # Build and Push apigateway Service
      - name: Build and Push Discovery
        uses: docker/build-push-action@v5
        with:
          context: ./Backend/APIGateway
          push: true
          tags: hemantbarole/micro-apigateway-service:latest
      
      # Build and Push hotel Service
      - name: Build and Push Discovery
        uses: docker/build-push-action@v5
        with:
          context: ./Backend/HotelServices
          push: true
          tags: hemantbarole/micro-hotel-service:latest
      
     # Build and Push rating Service
      - name: Build and Push Discovery
        uses: docker/build-push-action@v5
        with:
          context: ./Backend/RatingServices
          push: true
          tags: hemantbarole/micro-rating-service:latest
      
       # Build and Push user Service
      - name: Build and Push Discovery
        uses: docker/build-push-action@v5
        with:
          context: ./Backend/UserService
          push: true
          tags: hemantbarole/micro-user-service:latest